### ISSUE TITLE
fresh install ubuntu 14.04

### ISSUE THREAD

**Issue by txt3rob** [zgelici/FOS-Streaming#12]
Getting the below errors in nginx logs on a fresh install.

also noticed that there is no vendor folder from what ever is being installed by composer.

```
2015/10/30 21:41:00 [notice] 13880#0: *19 "^/(.*)/(.*)/(.*)$" does not match "/install.php", client: 127.0.0.1, server: , request: "GET /install.php?install HTTP/1.1", host: "127.0.0.1:8000"
2015/10/30 21:41:00 [error] 13880#0: *19 FastCGI sent in stderr: "PHP message: PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/nginx/html/_start.php on line 4
PHP message: PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/local/nginx/html/_start.php on line 4" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /install.php?install HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "127.0.0.1:8000"
2015/10/30 21:41:22 [notice] 13880#0: *21 "^/(.*)/(.*)/(.*)$" does not match "/install.php", client: 127.0.0.1, server: , request: "GET /install.php?update HTTP/1.1", host: "127.0.0.1:8000"
2015/10/30 21:41:22 [error] 13880#0: *21 FastCGI sent in stderr: "PHP message: PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/nginx/html/_start.php on line 4
PHP message: PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/local/nginx/html/_start.php on line 4" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /install.php?update HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "127.0.0.1:8000"
2015/10/30 21:41:26 [notice] 13880#0: *23 "^/(.*)/(.*)/(.*)$" does not match "/", client: 151.227.216.224, server: , request: "GET / HTTP/1.1", host: "mystreamer:8000"
2015/10/30 21:41:26 [notice] 13880#0: *23 "^/(.*)/(.*)/(.*)$" does not match "/index.php", client: 151.227.216.224, server: , request: "GET / HTTP/1.1", host: "mystreamer:8000"
2015/10/30 21:41:26 [error] 13880#0: *23 FastCGI sent in stderr: "PHP message: PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/nginx/html/_start.php on line 4
PHP message: PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/local/nginx/html/_start.php on line 4" while reading response header from upstream, client: 151.227.216.224, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mystreamer:8000"
2015/10/30 21:42:18 [info] 13880#0: *25 client closed connection while waiting for request, client: 151.227.216.224, server: 0.0.0.0:8000
2015/10/30 21:42:18 [info] 13880#0: *26 client closed connection while waiting for request, client: 151.227.216.224, server: 0.0.0.0:8000
2015/10/30 21:42:18 [info] 13880#0: *28 client closed connection while waiting for request, client: 151.227.216.224, server: 0.0.0.0:8000
2015/10/30 21:42:18 [info] 13880#0: *27 client closed connection while waiting for request, client: 151.227.216.224, server: 0.0.0.0:8000
2015/10/30 21:42:18 [info] 13880#0: *29 client closed connection while waiting for request, client: 151.227.216.224, server: 0.0.0.0:8000
```

i fixed on thing by doing 

```
apt-get install php5-cli -y
```

then 

```
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
```

**Comment by txt3rob** [comment]
fixed by doing 

```
composer require illuminate/database
```

you might need to add this to the install file

**Comment by txt3rob** [comment]
adding a stream i get which i presume i need to add a transcode profile first?

```
2015/10/30 21:59:47 [error] 13880#0: *81 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'trans_id' in 'field list'' in /usr/local/nginx/html/vendor/illuminate/database/Connection.php:390
Stack trace:
#0 /usr/local/nginx/html/vendor/illuminate/database/Connection.php(390): PDO->prepare('insert into `st...')
#1 /usr/local/nginx/html/vendor/illuminate/database/Connection.php(644): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `st...', Array)
#2 /usr/local/nginx/html/vendor/illuminate/database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('insert into `st...', Array, Object(Closure))
#3 /usr/local/nginx/html/vendor/illuminate/database/Connection.php(391): Illuminate\Database\Connection->run('insert into `st...', Array, Object(Closure))
#4 /usr/local/nginx/html/vendor/illuminate/database/Connection.php(347): Illuminate\Database\Connection->statement('insert into `st" while reading response header from upstream, client: 151.227.216.224, server: , request: "POST /manage_stream.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mystreamer:8000", referrer: "http://streamer.robserver.com:8000/manage_stream.php"
```

**Comment by txt3rob** [comment]
fixed by doing the install update script

**Comment by zgelici** [comment]
Nice, good job.
